### ISSUE TITLE
Use on non-windows OS?

### ISSUE THREAD

**Issue by psimsa** [Sicos1977/TesseractOCR#46]
Just wondering - is there a switch somewhere that would allow me to use the nuget on Linux? ("bring-your-own-linux-compiled-binaries" kind of thing)

**Comment by Sicos1977** [comment]
It should work on linux. If I remeber correctly it will try to search for the tesseract files with an .so extension. But what you can do is turn on debug logging and see where it is trying to find the leptonica en tesseract stuff. There should be no issue with the C# code because that is build to work Windows, Linux and MacOS.

**Comment by Sicos1977** [comment]
Any updates?

**Comment by Sicos1977** [comment]
No response ... closed.
